<?php

declare(strict_types=1);

namespace App\Enum;

enum ErrorCode: string
{
    case AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS';
    case AUTH_ALREADY_AUTHENTICATED = 'AUTH_ALREADY_AUTHENTICATED';
    case RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED';
    case VALIDATION_FAILED = 'VALIDATION_FAILED';
    case REGISTRATION_FAILED = 'REGISTRATION_FAILED';
}
