framework:
    rate_limiter:
        register:
            policy: fixed_window
            limit: 10
            interval: "1 hour"

        api:
            policy: token_bucket
            limit: 60
            rate: { amount: 60, interval: "1 minute" }

when@test:
    framework:
        rate_limiter:
            register:
                policy: fixed_window
                limit: 3
                interval: "1 hour"
            api:
                policy: token_bucket
                limit: 5
                rate: { amount: 5, interval: "1 minute" }
