---
services:
  php:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: frankenphp_dev
    restart: unless-stopped
    environment:
      SERVER_NAME: ${SERVER_NAME}, php:80
      DEFAULT_URI: https://${SERVER_NAME}:${HTTPS_PORT}
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_VERSION: ${MARIADB_VERSION}
      MARIADB_CHARSET: ${MARIADB_CHARSET}
      REDIS_URL: ${REDIS_URL}
      # Run "composer require symfony/mercure-bundle" to install and configure the Mercure integration
      MERCURE_URL: ${CADDY_MERCURE_URL:-http://php/.well-known/mercure}
      MERCURE_PUBLIC_URL: ${CADDY_MERCURE_PUBLIC_URL:-https://${SERVER_NAME}:${HTTPS_PORT}/.well-known/mercure}
      MERCURE_JWT_SECRET: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - name: http
        target: 80
        published: ${HTTP_PORT}
        protocol: tcp
      - name: https
        target: 443
        published: ${HTTPS_PORT}
        protocol: tcp
      - name: http3
        target: 443
        published: ${HTTP3_PORT}
        protocol: udp
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy

  database:
    image: mariadb:lts
    restart: unless-stopped
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: 1
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_USER: ${MARIADB_USER}
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - database_data:/var/lib/mysql:rw
    ports:
      - 3306

  redis:
    image: redis:alpine
    restart: unless-stopped
    command: redis-server --save "" --requirepass ${REDIS_PASSWORD}
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "--no-auth-warning", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

# Mercure is installed as a Caddy module, prevent the Flex recipe from installing another service
###> symfony/mercure-bundle ###
###< symfony/mercure-bundle ###

volumes:
  caddy_data:
  caddy_config:
  database_data:
###> symfony/mercure-bundle ###
###< symfony/mercure-bundle ###
