---
# Production environment override
services:
  php:
    image: ${IMAGES_PREFIX:-}app-php-prod
    build:
      target: frankenphp_prod
    environment:
      PORT: ${PORT:-8080}
      APP_SECRET: ${APP_SECRET}
      MERCURE_PUBLISHER_JWT_KEY: ${MERCURE_PUBLISHER_JWT_KEY}
      MERCURE_SUBSCRIBER_JWT_KEY: ${MERCURE_SUBSCRIBER_JWT_KEY}
      CADDY_SECURITY_HEADERS: |
        header {
            Strict-Transport-Security "max-age=31536000; includeSubDomains"
            X-Content-Type-Options "nosniff"
            Referrer-Policy "strict-origin-when-cross-origin"
            X-Frame-Options "DENY"
        }
      MERCURE_EXTRA_DIRECTIVES: ""
      MERCURE_PUBLIC_URL: "https://${SERVER_NAME}/.well-known/mercure"
    ports:
      - target: ${PORT:-8080}
        published: ${PORT:-8080}
        protocol: tcp
