<?php

declare(strict_types=1);

namespace App\Error;

enum ErrorCode: string
{
    case AUTH_DUPLICATE_EMAIL = 'AUTH_DUPLICATE_EMAIL';
    case AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS';
    case AUTH_NOT_AUTHENTICATED = 'AUTH_NOT_AUTHENTICATED';
    case VALIDATION_FAILED = 'VALIDATION_FAILED';
    case WORKSPACE_NAME_TOO_LONG = 'WORKSPACE_NAME_TOO_LONG';
    case WORKSPACE_NOT_FOUND = 'WORKSPACE_NOT_FOUND';
    case WORKSPACE_FORBIDDEN = 'WORKSPACE_FORBIDDEN';
    case RATE_LIMITED = 'RATE_LIMITED';
    case INTERNAL_ERROR = 'INTERNAL_ERROR';
}
