name: Security Audit

permissions:
  contents: read

on:
  schedule:
    - cron: "0 6 * * 1"
  workflow_dispatch: {}

jobs:
  frontend-audit:
    name: Frontend Audit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7.0.1

      - name: Setup Node app
        uses: ./.github/actions/setup-node-app

      - name: Run audit
        working-directory: frontend
        run: pnpm audit --audit-level=high

  api-audit:
    name: API Audit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7.0.1

      - name: Setup PHP app
        uses: ./.github/actions/setup-php-app

      - name: Run audit
        working-directory: api
        run: composer audit
